Wallet api
Topl/BramblDart pull request #106
Opened 2023-08-18 20:16 UTC by ultimaterex

Includes necessary changes for the wallet API

Turns out codecspec wasn't actually tested in a previous commit so those tests have been added now. lots of json related bug fixing included

2023-08-21 15:13 UTC, KalervoHyyppa requested changes
Please see comments

2023-08-21 15:13 UTC, KalervoHyyppa commented on lib/src/brambl/wallet/wallet_api.dart
> +  Future<Either<WalletApiFailure, NewWalletResult>> createNewWallet(List<int> password,
Why does this require a password to create a new wallet?

2023-08-29 07:27 UTC, ultimaterex commented on lib/src/brambl/data_api/wallet_key_api_algebra.dart
> +  Future<Either<WalletKeyException, void>> saveMainKeyVaultStore(VaultStore mainKeyVaultStore, String name);
You're correct in your assumption that a Either return function _should_ never throw;

An `Either` is used to represent a value that could be one of two possibilities: either a success value or an error value. in this case you'd be expected to check for errors in a functional way instead of the traditional try/catch approach.

You have various ways of doing this, the two I'd reccomend would be the following:

1. Consider the function `saveMainKeyVaultStore()` this will return a WalletKeyException or a void. adding .get() to the result will either return the value of right, or it will throw the left value.

2. You could also check if the return value of this function is the left value and in that case halt operations and handle this WalletKeyException type in your own way.


The function signatures are written this way to keep the documentation as close to the Scala source as possible and keep the interfaces as similar as possible. If you'd prefer a more traditional approach like the code below I could add a alternative interface in the future.

```
/// to manage the names of the wallet identities if multiple will be used.
///
/// If persisting fails due to an underlying cause, throws a [WalletKeyException].
Future saveMainKeyVaultStore(VaultStore mainKeyVaultStore, String name);
```

On a separate note, using void as a successful return type is problematic as dart doesn't support static runtime checking for void as it's a odd type. I've migrated away from void and added a generic type called "Unit" this will indicate a generic success.

2023-08-29 07:32 UTC, ultimaterex commented on lib/src/brambl/wallet/wallet_api.dart
> +  Future<Either<WalletApiFailure, NewWalletResult>> createNewWallet(List<int> password,
I believe this is because of us following the BIP39 specification which recommends using a passphrase to harden your wallet in case your seed phrase gets stolen.

https://vault12.com/securemycrypto/crypto-security-basics/what-is-a-wallet-passphrase/

2023-09-01 20:22 UTC, ultimaterex commented
I've fixed the remaining bugs regarding wallet key derivation in the API, closing this PR

2023-09-01 20:23 UTC, merged